name: Build and deploy ASP.NET Core app to an Azure Web App

env:
    AZURE_WEBAPP_NAME: coordinatorapi
    AZURE_WEBAPP_PACKAGE_PATH: "."
    DOTNET_VERSION: "10.0.x"

on:
    push:
        branches: ["main"]
    workflow_dispatch:

permissions:
    contents: read

jobs:
    build:
        name: Build and deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6

            - name: Set up .NET
              uses: actions/setup-dotnet@v5
              with:
                  dotnet-version: ${{ env.DOTNET_VERSION }}

            - name: Set up dependency caching for faster builds
              uses: actions/cache@v5
              with:
                  path: ~/.nuget/packages
                  key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-nuget

            - name: Run dotnet build
              run: dotnet build --configuration Release ./coordinatorapi/src/CoordinatorApi/CoordinatorApi.csproj

            - name: Run dotnet publish
              run: dotnet publish -c Release -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/app ./coordinatorapi/src/CoordinatorApi/CoordinatorApi.csproj

            - name: Deploy to Azure Web App
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v2
              with:
                  app-name: ${{ env.AZURE_WEBAPP_NAME }}
                  publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
                  package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/app
